# Generated by Django 3.2.4 on 2021-06-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='SKU'),
        ),
    ]
