# Generated by Django 3.2.4 on 2021-06-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210625_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombreMarca', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Marca')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(blank=True, default='sinfoto.jpg', null=True, upload_to='images/', verbose_name='Imagen del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=80, verbose_name='Categoria'),
        ),
    ]
