# Generated by Django 3.2.4 on 2021-06-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210625_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.marca'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id marca'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.CharField(default=None, max_length=200, verbose_name='nombre de Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=None, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=None, verbose_name='Stock'),
        ),
    ]
